---
- name: Create VLANs
  cisco.ios.ios_vlans:
    config:
      - vlan_id: "{{ item.id }}"
        name: "{{ item.name }}"
        state: active
    state: merged
  loop: "{{ vlans | default([]) }}"
  loop_control:
    label: "VLAN {{ item.id }}"
  when: vlans is defined

- name: Configure interface description and admin state
  cisco.ios.ios_interfaces:
    config:
      - name: "{{ item.name }}"
        description: "{{ item.description | default(omit) }}"
        enabled: true 
    state: merged
  loop: "{{ basis_interfaces + interfaces | default([]) }}"
  loop_control:
    label: "{{ item.name }}"

- name: Configure interfaces
  vars:
    access_interfaces: "{{ basis_interfaces | default([]) | selectattr('mode', 'defined') | selectattr('mode', 'equalto', 'access') | list }}"
    trunk_interfaces: "{{ basis_interfaces | default([]) | selectattr('mode', 'defined') | selectattr('mode', 'equalto', 'trunk') | list }}"
  
  block:
    - name: Configure SVIs
      cisco.ios.ios_l3_interfaces:
        config:
          - name: "{{ item.name }}"
            ipv4: "{{ item.ipv4 }}"
        state: merged
      loop: "{{ interfaces | default([]) }}"
      loop_control:
        label: "{{ item.name }}"
      when:
        - item.ipv4 is defined

    - name: Configure interfaces
      cisco.ios.ios_l2_interfaces:
        config:
          - name: "{{ item.name }}"
            mode: "{{ item.mode }}"
            access: "{{ {'vlan': item.access_vlan | int} if item.mode == 'access' else omit }}"
            trunk: "{{ {'allowed_vlans': item.trunk_allowed_vlans, 'encapsulation': item.trunk_encapsulation | default(omit)} if item.mode == 'trunk' else omit }}"
        state: merged
      loop: "{{ access_interfaces + trunk_interfaces }}"
      loop_control:
        label: "{{ item.name }}"