interfaces:
  - name: Vlan10
    description: Management SVI VLAN10
    ipv4:
      - address: 192.168.30.65/26
  - name: Vlan20
    description: Management SVI VLAN20
    ipv4:
      - address: 192.168.30.129/26
  - name: Vlan30
    description: Management SVI VLAN30
    ipv4:
      - address: 192.168.30.193/26
  - name: Vlan99
    description: Management SVI
    ipv4:
      - address: 192.168.30.5/26

static_routes:
  - address_families:
      - afi: ipv4
        routes:
          - dest: 0.0.0.0/0
            next_hops:
              - forward_router_address: 192.168.30.1
