interfaces:
  - name: Vlan10
    description: Management SVI VLAN10
    ipv4:
      - address: 192.168.10.65/26
  - name: Vlan20
    description: Management SVI VLAN20
    ipv4:
      - address: 192.168.10.129/26
  - name: Vlan30
    description: Management SVI VLAN30
    ipv4:
      - address: 192.168.10.193/26
  - name: Vlan99
    description: Management SVI
    ipv4:
      - address: 192.168.10.5/26
  - name: GigabitEthernet0/0
    description: Verdieping 1 Gent
    mode: access
    access_vlan: 10
  - name: GigabitEthernet0/1
    description: Verdieping 2 Gent
    mode: access
    access_vlan: 20
  - name: GigabitEthernet0/2
    description: Verdieping 3 Gent
    mode: access
    access_vlan: 30
  - name: GigabitEthernet0/3
    description: Uplink Trunk
    mode: trunk
    trunk_allowed_vlans: "1,10,20,30,99"
    encapsulation: dot1q

static_routes:
  - address_families:
      - afi: ipv4
        routes:
          - dest: 0.0.0.0/0
            next_hops:
              - forward_router_address: 192.168.10.1
