all:
  children:
  
    routers:
      hosts:
        CompanyRouter:
          ansible_host: 192.168.72.10
          role_nat: true
          nat_inside: GigabitEthernet0/3
          nat_outside:
            - GigabitEthernet0/0
            - GigabitEthernet0/1
            - GigabitEthernet0/2

        GentRouter:
          ansible_host: 10.10.10.2

        AntwerpenRouter:
          ansible_host: 10.10.20.2

        BrusselRouter:
          ansible_host: 10.10.30.2

    switches:
      children:
        uplink_switches:
        edge_switches:

    uplink_switches:
      hosts:
        GentUplink:
          ansible_host: 192.168.10.5
        AntwerpenUplink:
          ansible_host: 192.168.20.5
        BrusselUplink:
          ansible_host: 192.168.30.5

# groepen per site
    Gent:
      children:
        gent_routers:
        gent_switches:

    gent_routers:
      hosts:
        GentRouter:

    gent_switches:
      hosts:
        GentUplink:


    Antwerpen:
      children:
        antwerpen_routers:
        antwerpen_switches:

    antwerpen_routers:
      hosts:
        AntwerpenRouter:

    antwerpen_switches:
      hosts:
        AntwerpenUplink:

    Brussel:
      children:
        brussel_routers:
        brussel_switches:

    brussel_routers:
      hosts:
        BrusselRouter:

    brussel_switches:
      hosts:
        BrusselUplink: